// REPOS Action for datas

export const SET_REPOS = 'SET_REPOS';
export const EDIT_REPO = 'EDIT_REPO';
export const ADD_REPOS = 'ADD_REPOS';
export const DELETE_REPO = 'DELETE_REPO';
// Fetch Data Actions
export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_INDIVIDUAL_REPO = 'FETCH_INDIVIDUAL_REPO';
export const SET_COLUMNS = 'SET_COLUMNS'
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_ITEM_POSITION_IN_SAME_CONTAINER = 'CHANGE_ITEM_POSITION_IN_SAME_CONTAINER'
export const CHANGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER = 'CHNAGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER'