// REPOS Action for datas
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const ADD_CONTAINER = 'ADD_CONTAINER'
export const EDIT_CONTAINER = 'EDIT_CONTAINER'
export const DELETE_CONTAINER = 'DELETE_CONTAINER'
export const CHANGE_ITEM_POSITION_IN_SAME_CONTAINER =
  'CHANGE_ITEM_POSITION_IN_SAME_CONTAINER'
export const CHNAGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER =
  'CHNAGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER'
export const CHANGE_COLUMN = 'CHANGE_COLUMN'
export const ADD_REPO = 'ADD_REPO'
export const EDIT_REPO = 'EDIT_REPO'
export const DELETE_REPO = 'DELETE_REPO'
export const SET_REPOS = 'SET_REPOS'
export const SET_COLUMNS = 'SET_COLUMNS'

// Fetch Data Actions
export const FETCH_REPOS = 'FETCH_REPOS'
export const FETCH_INDIVIDUAL_REPO = 'FETCH_INDIVIDUAL_REPO'


export const SET_INITIAL_STATE_FETCH_REDUCER = 'SET_INITIAL_STATE_FETCH_REDUCER'

export const SET_INITIAL_STATE_REPO_REDUCER = 'SET_INITIAL_STATE_REPO_REDUCER'
